export const TIMER = [
	{ name: "Right now", value: "0" },
	{ name: "In 1 minute", value: "1" },
	{ name: "In 5 minutes", value: "5" },
	{ name: "In 10 minutes", value: "10" },
	{ name: "In 15 minutes", value: "15" },
	{ name: "In 30 minutes", value: "30" },
	{ name: "In 1 hour", value: "60" },
	{ name: "In 2 hours", value: "120" },
	{ name: "In 3 hours", value: "180" },
	{ name: "In 4 hours", value: "240" },
	{ name: "In 6 hours", value: "360" },
	{ name: "In 8 hours", value: "480" },
	{ name: "In 12 hours", value: "720" },
]
